capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('website.urls'))
]

capstone/website/urls.py
from django.urls import path, include
from . import views


app_name = "website"
urlpatterns = [
    path('', views.user_login, name="user_login"),
    path('authenticatation/', views.authenticatation, name="authenticatation"),
    path('homepage/', views.homepage, name="homepage"),
    path('area_serviced/', views.area_serviced, name="area_serviced"),
    path('biography/', views.biography, name="biography"),
    path('endorsements/', views.endorsements, name="endorsements"),
    path('add_endorser/', views.add_endorser, name="add_endorser")
]

capstone/website/models.py
from django.db import models

class Endorser(models.Model):
    """Module that captures the name and surname of all endorsers and stores it in the database.
    """

    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name} {self.surname}'

capstone/website/forms.py
from django.forms import ModelForm
from .models import Endorser

class EndorserForm(ModelForm):
    class Meta:
        model = Endorser
        fields = '__all__'

capstone/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Endorser
from .forms import EndorserForm

def user_login(request):
    return render(request, 'login.html')

def authenticatation(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('website:user_login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('website:homepage')
        )

def homepage(request):
    return render (request, "homepage.html")

def area_serviced(request):
    return render (request, "area_serviced.html")

def biography(request):
    return render (request, "biography.html")

def endorsements(request):
    latest_endorser_list = Endorser.objects.all()
    context = {'latest_endorser_list': latest_endorser_list}
    return render (request, "endorsements.html", context)

def add_endorser(request):
    form = EndorserForm

    if request.method == "POST":
        form = EndorserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('website:homepage'))
        
    context= {'form': form}
    return render(request, 'add_endorser.html', context)

capstone/website/templates/add_endorser.html
{% block content %}

<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<div class = "row">
	<div class = "col-md-3">
		<h2>Add Endorser</h2>
	</div>
</div>

<form action="" method="post">
	{% csrf_token %}
	<div class = "row">
		<div class = "col-md-3">
		{{form.as_p}}
		</div>
	</div>
	
	<div class = "row">
		<div class = "col-md-3">
		<button type="submit" value="">Add</button>
		</div>
	</div>
</form>

{% endblock content %}

capstone/website/templates/area_serviced.html
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<div class = "row" align= "center">
	<div class = "col-md-12">
		<h1> Below is a list of all planets that I will be serving, click on them to view various facts about each one! </h1>
	</div>
</div>

<br>

<div class = "row" align= "center">
	<div class = "col-md-6">
		<a href="https://rickandmorty.fandom.com/wiki/Blips_and_Chitz">
		<img width="500" height="400" src="https://res.cloudinary.com/teepublic/image/private/s--96D3UWgj--/t_Preview/b_rgb:484849,c_limit,f_jpg,h_630,q_90,w_630/v1446244127/production/designs/295626_1.jpg">
		</a>
		<h2>Blips and Chitz</h2>
	</div>
	
	<div class = "col-md-6">
		<a href="https://rickandmorty.fandom.com/wiki/Snake_Planet">
		<img width="500" height="400" src="https://static.wikia.nocookie.net/rickandmorty/images/4/43/Snake_Planet.png/revision/latest/scale-to-width-down/1000?cb=20191217203922">
		</a>
		<h2>Snake Planet</h2>
	</div>
</div>

<br>

<div class = "row" align= "center">
	<div class = "col-md-12">
		<a href="https://rickandmorty.fandom.com/wiki/Resort_planet">
		<img width="500" height="400" src="https://static.wikia.nocookie.net/rickandmorty/images/d/d7/S3e5_resort_planet.png/revision/latest/scale-to-width-down/1000?cb=20171119204625">
		</a>
		<h2>Resort Planet</h2>
	</div>
</div>

capstone/website/templates/biography.html
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<br><br><br><br><br>

<div class = "row" align="center">
	<div class = "col-md-12">
		<h1> About Me </h1>
	</div>
</div>

<div class = "row" align="center">
	<div class = "col-md-12">
		Name: Rick Sanchez<br>
		Born: Earth C-137<br>
		Experience: Dealt with Intergalactic Government for many years<br>
		Motto: Wubba Lubba Dub Dub<br>
		<img width="400" height="400" src="https://th.bing.com/th/id/R.5b75b9cd5dc886a32249cc4b5223fdfb?rik=FinyhO0CyH6DBg&pid=ImgRaw&r=0">
	</div>
</div>
		

capstone/website/templates/endorsements.html
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<div class = "row">
	<div class = "col-md-12">
		This is a list of all private endorsers that are backing me in the upcoming elections, you could be next!
		<br><br>
	</div>
</div>

{% if latest_endorser_list %}

<div class = "row">
	<div class = "col-md-4">
		{% for endorser in latest_endorser_list %}
			<ul>
				<li>
					{{ endorser }}
				</li>
			</ul>
		{% endfor %}
	</div>
</div>
	
{% else %}
<div class = "row">
	<div class = "col-md-4">
		None
	</div>
</div>

{% endif %}

<br>
<div class = "row">
	<div class = "col-md-4">
		<a href = "{% url 'website:add_endorser' %}">
		Add Endorser
		</a>
	</div>
</div>

capstone/website/templates/homepage.html
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

	<style>
		body {
		background-image: url('https://www.rollingstone.com/wp-content/uploads/2020/02/Dem_5.0Wz.jpg');
		background-attachment: fixed;
		background-size: 100% 100%;
		}
	</style>
</head>

<br>

<body>
	<div class = "row" align="center">
		<div class = "col-md-4">
			<a href = "{% url 'website:biography' %}">
			<button>See Biography</button>
			</a>
		</div>

		<div class = "col-md-4">
			<a href = "{% url 'website:area_serviced' %}">
			<button>See Planets Serviced</button>
			</a>
		</div>

		<div class = "col-md-4">
			<a href = "{% url 'website:endorsements' %}">
			<button>See Endorsements</button>
			</a>
		</div>
	</div>

	<br><br>

	<div class = "row" align="center">
		<div class = "col-md-12">
			<h1 style="color:White"><b>Me for Governor!!!</b></h1>
		</div>
	</div>
</body>

capstone/website/templates/login.html
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<div class = "row">
	<div class = "col-md-2">
		<h1> Login </h1>
	</div>
</div>

<form action="{% url 'website:authenticatation' %}" method="post">
	{% csrf_token %}
	
	<div class = "row">
		<div class = "col-md-2">
			<label>Username</label>
			<input type="text" name="username" placeholder="User" required>
			<br/><br/>
		</div>
	</div>
	
	<div class = "row">
		<div class = "col-md-2">
			<label>Password</label>
			<input type="password" name="password" required>
			<br/><br/>
		</div>
	</div>
	
	<div class = "row">
		<div class = "col-md-2">
			<input type="submit" value="Login" />
		</div>
	</div>
</form>